language: shell
dist: focal

install:
  - source ./texlive/texlive_install.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

# Change working directory so including files will work
before_script: cd $TRAVIS_BUILD_DIR/
script:
  # Texliveonfly will download packages automatically
  - texliveonfly main.tex
  # You can use latexmk to automatically handle bibtex and references (recommended)
  - latexmk -pdf main.tex